# List of RDM PIDs

rdm_pid_list = {
    # Category – Network Management
    '0x0001': 'DISC_UNIQUE_BRANCH',
    '0x0002': 'DISC_MUTE',
    '0x0003': 'DISC_UN_MUTE',
    '0x0010': 'PROXIED_DEVICES',
    '0x0011': 'PROXIED_DEVICE_COUNT',
    '0x0015': 'COMMS_STATUS',
    # Category - Status Collection
    '0x0020': 'QUEUED_MESSAGE',
    '0x0030': 'STATUS_MESSAGES',
    '0x0031': 'STATUS_ID_DESCRIPTION',
    '0x0032': 'CLEAR_STATUS_ID',
    '0x0033': 'SUB_DEVICE_STATUS_REPORT_THRESHOLD',
    # Category - RDM Information
    '0x0050': 'SUPPORTED_PARAMETERS',
    '0x0051': 'PARAMETER_DESCRIPTION',
    # Category – Product Information
    '0x0060': 'DEVICE_INFO',
    '0x0070': 'PRODUCT_DETAIL_ID_LIST',
    '0x0080': 'DEVICE_MODEL_DESCRIPTION',
    '0x0081': 'MANUFACTURER_LABEL',
    '0x0082': 'DEVICE_LABEL',
    '0x0090': 'FACTORY_DEFAULTS',
    '0x00A0': 'LANGUAGE_CAPABILITIES',
    '0x00B0': 'LANGUAGE',
    '0x00C0': 'SOFTWARE_VERSION_LABEL',
    '0x00C1': 'BOOT_SOFTWARE_VERSION_ID',
    '0x00C2': 'BOOT_SOFTWARE_VERSION_LABEL',
    # Category - DMX512 Setup
    '0x00E0': 'DMX_PERSONALITY',
    '0x00E1': 'DMX_PERSONALITY_DESCRIPTION',
    '0x00F0': 'DMX_START_ADDRESS',
    '0x0120': 'SLOT_INFO',
    '0x0121': 'SLOT_DESCRIPTION',
    '0x0122': 'DEFAULT_SLOT_VALUE',
    # Category – Sensors
    '0x0200': 'SENSOR_DEFINITION',
    '0x0201': 'SENSOR_VALUE',
    '0x0202': 'RECORD_SENSORS',
    # Category – Power/Lamp Settings
    '0x0400': 'DEVICE_HOURS',
    '0x0401': 'LAMP_HOURS',
    '0x0402': 'LAMP_STRIKES',
    '0x0403': 'LAMP_STATE',
    '0x0404': 'LAMP_ON_MODE',
    '0x0405': 'DEVICE_POWER_CYCLES',
    # Category - Display Settings 
    '0x0500': 'DISPLAY_INVERT',
    '0x0501': 'DISPLAY_LEVEL',
    # Category – Configuration 
    '0x0600': 'PAN_INVERT',
    '0x0601': 'TILT_INVERT',
    '0x0602': 'PAN_TILT_SWAP',
    '0x0603': 'REAL_TIME_CLOCK',
    # Category – Control
    '0x1000': 'IDENTIFY_DEVICE',
    '0x1001': 'RESET_DEVICE',
    '0x1010': 'POWER_STATE',
    '0x1020': 'PERFORM_SELFTEST',
    '0x1021': 'SELF_TEST_DESCRIPTION',
    '0x1030': 'CAPTURE_PRESET',
    '0x1031': 'PRESET_PLAYBACK',
}

esta_manufracturers_id = { 
    '0000': 'ESTA ',
    '0000': 'PLASA ',
    '0001': 'GEE ',
    '0002': 'Abstract AVR Ltd. ',
    '0003': 'Chromatech Lighting Co., Ltd. ',
    '0008': 'Guangdong Nanguang Photo & Video Systems Co., Ltd. ',
    '0009': 'Aputure Imaging Industries Co., Ltd. ',
    '000A': 'Interactive Imagination Ltd. ',
    '000B': 'Phospec Industries Inc.  ',
    '000C': 'WAC Lighting Co. ',
    '000D': 'Guangzhou Haoteng Lighting Co., Ltd. ',
    '000E': 'Yaoxing Lighting Equipment (Guanghzou）Co., Ltd. ',
    '000F': 'Shenzhen L-Thinker Technology Co., Ltd. ',
    '0010': 'Dongguan Mi Xing Electronic Technology Co., Ltd. ',
    '0011': 'Beijing Kedeshengye Technology Service Co., Ltd. ',
    '0012': 'Apex Pro Light Co., Ltd. ',
    '0013': 'Teixo BV ',
    '0014': 'SIRS Electronics, Inc. ',
    '0015': 'Lumencraft Lighting Solutions ',
    '0016': 'Shenzhen Xuntek Electronics Co., Ltd ',
    '0017': 'Ereimul ',
    '0018': 'Macroblock, Inc. ',
    '0019': 'Odelic Co., Ltd. ',
    '001A': 'DLL Ltd. ',
    '001B': 'Changsha Sunrise Electronic Technology Co. Ltd. ',
    '001C': 'Kindwin Technology (HK) Ltd. ',
    '001D': 'Luminator Technology Group ',
    '001E': 'Shenzhen Lumi Lime Technology Limited ',
    '0020': 'Wattle IT ',
    '0021': 'Electric Foundry Ltd. ',
    '0057': 'Blackbezt Lighting Technology Co., Ltd. ',
    '0058': 'Big Dipper Laser Science and Technology Co.,Ltd. ',
    '0059': 'Laysion Lighting Technology Co., Ltd. ',
    '005A': 'TPD Lighting ',
    '006A': 'AIMTECH Electronik Tasarim Ltd. Sti. ',
    '006B': 'SALZBRENNER media GmbH ',
    '006C': 'Flash-Butrym Sp.J. ',
    '006D': 'AA Tasarim Ltd. ',
    '006E': 'WHITEvoid GmbH ',
    '006F': 'AC Power Distribution/ACT Lighting Inc. ',
    '0070': 'Instalighting GmbH ',
    '0071': 'Guangzhou Huaxinyuan Electronics Co., Ltd. ',
    '0072': 'Guangzhou Zenith Aurora Lighting Co., Ltd. ',
    '0073': 'Meijay Technologies Co., Ltd. ',
    '0074': 'Thomann GmbH ',
    '0075': 'ODELI ',
    '0076': 'R. S. Schwarze Elektrotechnik Moderne Industrieelektronik GmbH ',
    '0077': 'CHAMP Licht ',
    '0078': 'Andy Lighting Technology Group Ltd. ',
    '0079': 'Leyard Opto Electronics Co., Ltd. ',
    '007A': 'Equivalent ',
    '007B': 'alurays lighting technology GmbH ',
    '007C': 'Huizhou Desay Intelligent Technology Co., Ltd. ',
    '007D': 'JMS Pro Light ',
    '007E': 'Stichting Hypar Collective ',
    '0080': 'Shenzhen AOTO Electronics Co., Ltd. ',
    '0081': 'Pino Solutions ',
    '0082': 'LKE Lasershowtechnik GmbH ',
    '0083': 'Guangzhou Bright Moon Technology Co., Ltd. ',
    '0084': 'LEDIXIS (Exalux brand) ',
    '0085': 'Guangzhou Nanshi Light Equipment Co., Ltd. ',
    '0086': 'Intella System Co., Ltd. ',
    '0087': 'LMBD ',
    '0088': 'Guangzhou YaFeng Optoelectronic Equipment Co., Ltd. ',
    '0089': 'Vulcan Lighting ',
    '008A': 'Guangzhou Lees Electronics Co., Ltd. ',
    '008B': 'Opto Tech Corporation ',
    '008C': 'LRX Lighting (Dwight Crane Ltd.) ',
    '008D': 'Guangzhou Minghao Electronic Technology Co., Ltd. ',
    '008E': 'Guangzhou Ao Mei Di Stage Lighting Equipment Co.,Ltd. ',
    '008F': 'Jiangmen Coolfish Technology Co., Ltd. ',
    '0090': 'Cyclops Lighting ',
    '0091': 'Guangzhou Shuozhi Optoelectronic Technology Co., Ltd. (Konelite) ',
    '0092': 'digiLED (UK) Ltd. ',
    '0093': 'Luminous Show Technology Ltd. ',
    '0094': 'Joinmax Display Technology Co., Ltd. ',
    '0095': 'Ningbo Jeg Lighting Tech Co., Ltd. ',
    '0096': 'SiChuan YuZhiWei Information Technology Lt., Co. ',
    '0097': 'AdvancedRay (Beijing) Science & Technology Industries Co., Ltd. ',
    '0098': 'Dedo Weigert Film GmbH ',
    '009A': 'Golden Sea Disco Light Manufacturer ',
    '009B': 'Guangzhou Jiawei Electronic Technology Co., Ltd. ',
    '009C': 'LuxBalance Lighting ',
    '009E': 'Guangzhou Flying Butterfly Stage Lighting Equipment Co., Ltd. ',
    '009F': 'Enedo Power SpA ',
    '00A0': 'Shenzhen Dicolor Optoelectronics Co., Ltd. ',
    '00A1': 'Creative Lighting And Sound Systems Pty Ltd. ',
    '00A2': 'EMP Designs Ltd. ',
    '00A3': 'GuangZhou Huanshi Lighting Equipment Co., Limited ',
    '00A4': 'SAKMA Electronica Industrial S.A.U.  ',
    '00A5': 'Delta Electronics, Inc. ',
    '00A6': 'Sensation Lighting Technology Co., Ltd. ',
    '00A7': 'Syncronorm GmbH ',
    '00A8': 'Iwasaki Electric Co., Ltd. ',
    '00A9': 'Richter Lighting Technologies GmbH  ',
    '00AA': 'Hangzhou Easun Technology Co., Ltd. ',
    '00AB': 'MFX Asia Co., Ltd ',
    '00AC': 'ZhouChuang Industrial Co. Limited ',
    '00AD': 'ColorDeve Co. Limited ',
    '00AE': 'Vitrulux Ltd ',
    '00AF': 'NanoPLC LLC ',
    '00B0': 'ARENA LUCI s.r.l. ',
    '00B1': 'Guangzhou Omarte Lighting Co., Ltd. ',
    '00B2': 'unonovesette srl ',
    '00B3': 'LANTERN ',
    '00B4': 'Lumos Design ',
    '00B5': 'Suga koubou Co., Ltd. ',
    '00B6': 'DiGidot Technologies BV ',
    '00B7': 'Bron Elektronik AG ',
    '00B8': 'Shenzhen Singba Light Technology Co., Ltd. ',
    '00B9': 'Guangzhou Baiyun District Sanjie Eletronic Stage Lighting Audio Equipment Factory ',
    '00BA': 'LiteGear Inc. ',
    '00BB': 'Digital Lighting Engineering & Design, LLC ',
    '00BC': 'Ambion GmbH (Ambrain) ',
    '00BD': 'numeo GmbH ',
    '00BE': 'The Light Luminary for Cine and TV S.L. (VELVET LIGHT)  ',
    '00BF': 'LumiOS (GTR Industries) ',
    '00C0': 'Foshan Yinhe Lanjing Lighting & Electrical Co., Ltd. ',
    '00C1': 'Jingchuang Water Technology ',
    '00C2': 'Ledogen ',
    '00C3': 'Xicato ',
    '00C4': 'Guangzhou Dahe Electronic Technology Co. Ltd. ',
    '00C5': 'DAGE Stage Lighting Master Co., Ltd. ',
    '00C6': 'Guangzhou Lantian Electronic Technology Co., Ltd. ',
    '00C7': 'THOR ',
    '00C8': 'Constell8 NV ',
    '00C9': 'Pangaea Technology ',
    '0101': 'St. Anne Engineering GmbH ',
    '0102': 'Bortis Elektronik ',
    '0103': 'Fontana Technologies ',
    '0104': 'Blizzard Lighting, LLC ',
    '0105': 'LIGHTHOW (SHANGHAI) Ltd. ',
    '0106': 'A.L.A. Equipment Company Ltd. ',
    '0107': 'Inventronics (Hangzhou), Inc. ',
    '0108': 'Haya Lighting Equipment Limited ',
    '0109': 'V-Productions ',
    '010A': 'Elektralite ',
    '010B': 'DesignLED Technology (HK) Co., Ltd. ',
    '010C': 'SES (Entertainment Services) Ltd. ',
    '010D': 'Lumos / DMLite ',
    '010E': 'Guangzhou ATON Lighting Technology Co.,Ltd ',
    '010F': 'Saco Technologies Inc. ',
    '0110': 'APF S.r.l. ',
    '0111': 'Radig Hard & Software ',
    '0112': 'RGB Lighting Equipment Co., Ltd. ',
    '0113': 'Airstar SAS ',
    '0114': 'BSL Lighting ',
    '0115': 'Kontrolcla Show Control S.L. ',
    '0116': 'SmoothLUX B.V. ',
    '0117': 'AD Toyo Lighting (Guangzhou) Co.,Ltd ',
    '0118': 'Vello Light Co., Ltd. ',
    '0119': 'Peter Schneyder Design Management GmbH ',
    '011A': 'Guangzhou Hotion Technology Co., Ltd. ',
    '011B': 'Jumptronic GmbH ',
    '011C': 'Letong Electronic (Guangzhou) Co., Ltd. ',
    '011D': 'Yangzhou Zhituo Lighting Vision Technology Co., Ltd.  ',
    '011E': 'Master LED ',
    '011F': 'STF s.r.l. ',
    '016C': 'LGR ',
    '016D': 'Hive Lighting ',
    '016E': 'Artled Technology Corp. ',
    '016F': 'SQD Lighting Co. Ltd  ',
    '018F': 'Guangzhou YiCheng Light Industry Ltd. ',
    '0190': 'Wizlogics Co., Ltd. ',
    '0191': 'Sycra Technologies ',
    '0199': 'Ocean LED Marine Ltd. ',
    '019A': 'TwoGain Electronics ',
    '019B': 'ElectroTAS Soluciones Profesionales ',
    '019F': 'DaisaLed Ltd. ',
    '01A0': 'Light With LED ',
    '01A1': 'Yuesheng Stage Light Limited ',
    '01A2': 'Art Lighting Production, s.r.o. ',
    '01A3': 'Dongguan Yongya Technology Co., Ltd ',
    '01A4': 'Custom Effects LED Solutions Inc. ',
    '01A5': 'MJ Lighting Co., Ltd. ',
    '01A6': 'Hengmei Lighting Technology Co., Ltd. ',
    '01A8': 'ZongDa Photoelectricity Science and Technology Co., Ltd. ',
    '01A9': 'Shenzhen Uniview LED Ltd. Co. ',
    '01AA': 'Vitec Videocom Inc. ',
    '01AB': 'Shanghai Euchips Industrial Co., Ltd. ',
    '01AC': 'DongGuan Phcistar Optoelectronics Technology Co., Ltd. ',
    '01AF': 'Hunan Minghe Opto Tech Co., Ltd. ',
    '01B1': 'Lightcare A/S ',
    '01B2': 'DJSI Schinstad ANS (Northern Light) ',
    '01B3': 'Ricardo Dias ',
    '01B4': 'Inventeq B.V. ',
    '01B5': 'Beijing Soft Rock Technology Development Co., Ltd. ',
    '01BE': 'BEN-RI Electronica S.A. ',
    '01C7': 'SCHIEDERWERK GmbH  ',
    '01C8': 'Guangzhou JINLIN Stage Lighting Equipment Co., Ltd.  ',
    '01C9': 'ALPHA LITE Inc. ',
    '01CA': 'CASCADE s.a.s. ',
    '01CB': 'ILT Italy SRL ',
    '01CC': 'Portman Custom Lights ',
    '01CD': 'Compulite Systems (2000) LTD ',
    '01CE': 'Railiks Enterprises ',
    '01CF': 'SRM Technik GmbH ',
    '01D0': 'Shanghai Semping Electronics Co., Ltd. ',
    '01D1': 'Yarilo Pro ',
    '01D2': 'GIP Innovation Tools GmbH ',
    '01D3': 'JSC Aksera ',
    '01D4': 'x-labs ',
    '01D5': 'Shenzhen Liantronics Co., Ltd ',
    '01D6': 'Argent Data Systems, Inc. ',
    '01D7': 'LIMEDIA ',
    '01D8': 'Daniel Large Lighting ',
    '01D9': 'Lightronics Inc. ',
    '01DA': 'Guangzhou Daisy Electronic Technology Co., Ltd.  ',
    '01DB': 'Logen Ltd. ',
    '01DC': 'LED Linear GmbH ',
    '01DD': 'Photonia srl ',
    '01DE': 'Guangzhou Baiyun Xinxiang Lighting Equipment Factory (XPRO LIGHT) ',
    '01DF': 'GuangZhou Dream Lighting Equipment Co., Ltd. ',
    '01E0': 'IBN Labs Ltd. ',
    '0200': 'Lighting Infusion LLC ',
    '0201': 'Blinkinlabs, LLC  ',
    '0202': 'Paul Heuts ',
    '0203': 'Artemide S.p.A ',
    '0204': 'LIGHTLINE Lasertechnik GmbH ',
    '0205': 'SmartShow UK ',
    '0206': 'Studio Due Light S.r.l. ',
    '0207': 'SILL LIGHTS GmbH ',
    '0208': 'Shenzhen Yuming Vision Technology Co., Ltd. ',
    '0209': 'ER Productions ',
    '020A': 'Seebacher GmbH ',
    '0210': 'Leksa Lighting Technologies Pvt. Ltd. ',
    '0211': 'Arkaos S.A. ',
    '0212': 'Frame The Space (FTSLED) ',
    '0213': 'Huizhou visionX Technology Co., Ltd. ',
    '0214': 'Impactrum ',
    '021A': 'WizzuLED by Scooon ',
    '0235': 'Company 235, LLC ',
    '0242': 'ABLELITE INTERNATIONAL ',
    '025B': 'Imlight-Showtechnic ',
    '026F': 'Acuity Brands Lighting Inc. ',
    '0280': 'Arrigo Lighting ',
    '028F': 'GRE Alpha Electronics Ltd. ',
    '02A0': 'LLC Likhoslavl Plant of Lighting Engineering (Svetotehnika) ',
    '02A1': 'LLC Moscow Experimental Lighting Plant (TeleMechanic) ',
    '02A2': 'OJSC Kadoshkinsky electrotechnical  ',
    '02A3': 'Big Bang Lightning ',
    '02A4': 'McNicoll Entertainment Systems ',
    '02AA': 'Jinnax Opto Technology Co., Ltd.  ',
    '02AB': 'Rift Labs ',
    '02AC': 'PSL Electronik Sanayi ve Ticaret A.S. ',
    '02B0': 'DMXControl-Projects e.V. ',
    '02BA': 'Chainzone Technology (Foshan) Co., Ltd. ',
    '02BD': 'RE-Engineering ',
    '02C8': 'Growflux LLC ',
    '02C9': 'Theatrixx Technologies ',
    '02CA': 'Acclaim Lighting ',
    '02CB': 'GVA Lighting, Inc. ',
    '02CC': 'Brightix ',
    '02D0': 'Winona Lighting ',
    '02D1': 'Hoffmeister Leuchten GmbH ',
    '02E1': 'Tait Towers Manufacturing Inc. ',
    '02E2': 'CLF Lighting BV. ',
    '02EA': 'd3 Technologies Ltd. ',
    '02EB': 'Amolvin Research & Development Lab. ',
    '02EC': 'Lutron Electronics ',
    '02ED': 'OpenLX SP Ltd. ',
    '02EE': 'Firma GUTKOWSKI - Gutkowski Jan ',
    '02EF': 'ABLETECH Co., Ltd. ',
    '02F0': 'iColor LED Shenzhen Co., Ltd. ',
    '02FF': 'Guangzhou Eway Stage Equipment Technology Co., Ltd. ',
    '0302': 'Swefog Technology Group AB ',
    '0303': 'Shanghai Moons Automation Control Co. Ltd ',
    '0305': 'DiCon Fiberoptics, Inc. ',
    '0306': 'feno GmbH ',
    '0307': 'Ledium Kft. ',
    '0308': 'ImageCue LLC  ',
    '030A': 'Shenzhen Colordreamer Tech Ltd. ',
    '030B': 'Guangzhou Wanrui Stage Light Equipment Co., Ltd. ',
    '030F': 'Guangzhou Litewise Lighting Equipments Co., Ltd. dba ""EK Lights"" ',
    '0311': 'Guangzhou PUGUANG Electronic Technology Co., Ltd. ',
    '0312': 'Guangzhou Xingkong Studio Lighting Co., Ltd. ',
    '032C': 'Carallon Ltd. ',
    '033A': 'Lux Lumen ',
    '034B': 'Rosstech Signals Inc. ',
    '038F': 'Strich Labs ',
    '0391': 'Alcorn McBride Inc. ',
    '0393': 'i2Systems ',
    '0394': 'Prism Projection ',
    '039B': 'Lightforce Lasertechnik ',
    '03A1': 'INAREX INC. ',
    '03A2': 'licht.team ',
    '03A8': 'ARTFOX ',
    '03AA': 'AIGA Electronic (GuangZhou) Co., Ltd. ',
    '03D5': 'eX Systems ',
    '03D6': 'i-Lumen ',
    '03FA': 'ART-DMX ',
    '0402': 'Exato ',
    '0404': 'Luminxa ',
    '0411': 'SoundSwitch ',
    '041C': 'IMLIGHT ',
    '0424': 'FLUX ECLAIRAGE ',
    '0440': 'Guangzhou VAS Lighting Co., Ltd. ',
    '044E': 'Ben Peoples Industries, LLC ',
    '044F': 'B2 Co., Ltd. ',
    '0455': 'Lamp & Pencil ',
    '048E': 'Krisledz Pte. Ltd. ',
    '048F': 'Grand Canyon LED Lighting System (Suzhou) Co., Ltd.  ',
    '04A6': 'MEB Veranstaltungstechnik GmbH ',
    '04A9': 'Edward J. Keefe Jr. ',
    '04B5': 'Major ',
    '04B6': 'IntiLED ',
    '04B8': 'Guangzhou Hongcai Stage Equipment Co., Ltd. ',
    '04C4': 'Ephesus Lighting, Inc. ',
    '04D7': 'Targetti Sankey Spa ',
    '04D8': 'Guangzhou Hong Yuan Electronic Technology Co., LTD. ',
    '04DD': 'Topstriving Photoelectricity Technology Co., Ltd. ',
    '04F0': 'SIGMA NET ',
    '04FC': 'Syncrolite LLC ',
    '050A': 'ChamSys Ltd. ',
    '051C': 'Ambitsel, Inc. ',
    '0520': 'ANLC Ltd ',
    '0529': 'OSRAM ',
    '0537': 'TERMINAL-COM ',
    '0540': 'EverBrighten Co., Ltd. ',
    '0555': 'Maresch Electronics ',
    '0556': 'RAYSYS ',
    '055F': 'PRO-SOLUTIONS ',
    '056B': 'COSMOLIGHT SRL ',
    '056C': 'Lumascape Lighting Industries ',
    '0573': 'JIAXING XINHUALI LIGHTING & SOUNDING CO., LTD. ',
    '0580': 'Innovation LED Limited ',
    '0586': 'K 5600, Inc. ',
    '0588': 'GuangZhou XiangMing Light Limited  ',
    '0592': 'MIRAGE B.V. ',
    '05A0': 'Stage Smarts AB ',
    '05A4': 'IMMOLAS ',
    '05AB': 'Shenzhen Lesan Lighting Co., Ltd.  ',
    '05B5': 'Turkowski GmbH  ',
    '05BC': 'CantoUSA ',
    '05CF': 'Brighten Technology Development Co., Ltd. ',
    '05D3': 'D-LED Illumination Technologies Ltd. ',
    '05E2': 'KORRO PLUS ',
    '05EB': 'GUANGZHOU BO WEI TE LIGHTING CO.LTD ',
    '05EF': 'Guangzhou Chai Yi Light Co., Ltd. ',
    '05F2': "O'Light ",
    '05F7': 'Immersive Design Studios Inc.  ',
    '0600': 'TELMIC Neo ',
    '0602': 'Guangzhou Jinhong Stage Lighting Equipment.Co.,ltd ',
    '0606': 'Guangzhou YiGuang Stage Lighting Co., Ltd. ',
    '0609': 'Diginet Control Systems Pty Ltd ',
    '060A': 'Kindwin Opto Electronic (ShenZhen) Co. Ltd ',
    '060B': 'Lighting Science Group (formerly LED Effects, Inc.) ',
    '060D': 'HANIL TNC CO.,LTD ',
    '0622': 'Lupo SRL ',
    '0623': 'JAS LIGHTING & SOUND CO., LTD. ',
    '0624': 'S4 Lights ',
    '0628': 'APEX PRO LIGHT CO.,LTD ',
    '062B': 'CKC Lighting Co., Ltd. ',
    '063A': 'AVM Belgium BVBA ',
    '063C': 'LaserNet ',
    '0644': 'COLEDER DISPLAY CO., LTD. ',
    '0645': 'MATSUMURA ELECTRIC MFG. CO. , LTD. ',
    '0650': 'RDC, Inc. d.b.a. LynTec ',
    '0653': 'USAI, LLC ',
    '0654': 'HUNAN XIANG CAIXU FILM AND TELEVISION CULTURE CO.LTD ',
    '0658': 'AZCOLOR LITE CO., LIMITED ',
    '065E': 'OFilms ',
    '0660': 'QSTECH CO.,LTD ',
    '066F': 'GUANGZHOU CY LIGHTING EQUIPMENT CO.,LTD ',
    '067A': 'Inster Co, Ltd ',
    '067C': 'LOTRONIC SA ',
    '0682': 'Beijing Ming Rui Lighting Technology Co., Ltd.  ',
    '0684': 'LEDART LLC ',
    '0685': 'IBL/ESD-Datentechnik GmbH ',
    '068E': 'GUANGZHOU TEANMA STAGE LIGHTING FACTORY ',
    '0696': 'SHENZHEN HOION LIGHTING CO.,LTD ',
    '06A0': 'Light.Audio.Design ',
    '06A1': 'ProTec GmbH ',
    '06A3': 'RODLIGHT ALBRECHT SILBERBERGER ',
    '06AC': 'GOLVER PROJECTS S.L. ',
    '06AE': 'CANARA LIGHTING INDUSTRIES PVT LTD ',
    '06AF': 'ZHEJIANG JINGRI TECHNOLOGY CO.,LTD ',
    '06B3': 'NANOLUMENS, INC. ',
    '06B6': 'GUANGDONG VSHINE LIGHTING TECHNOLOGY CO.,LTD ',
    '06B9': 'GUANGZHOU DASEN LIGHTING CORPORATION LIMITED ',
    '06C4': 'RHENAC Systems GmbH ',
    '06C7': 'L&L Luce&Light ',
    '06CE': 'American-Pro International ',
    '06D1': 'BIRUN ELECTRONIC INDUSTRIAL CO., LTD ',
    '06D2': 'LIGHTSTAR (BEIJING) ELECTRONIC CORPORATION ',
    '06E0': 'SHENZHEN LONGRUN OPTOELECTRONIC CO., LTD ',
    '06E1': 'Burck IT GmbH & Co. KG ',
    '06E4': 'Dydell B.V. ',
    '06E6': 'Equipson S.A. ',
    '06EC': 'SISTEMA Jsc ',
    '06F0': 'CTG sp. z o.o. ',
    '0702': 'Drinelec ',
    '0707': 'Conceptinetics Technologies and Consultancy Ltd. ',
    '0708': 'AK-LIGHT ',
    '070C': 'Pixout SIA ',
    '070D': 'Lumenwerx ULC ',
    '070F': 'Theatrelight New Zealand ',
    '0710': 'D.T.S. Illuminazione srl ',
    '0712': 'Laser Imagineering GmbH ',
    '071F': 'Moss LED Inc ',
    '0724': 'PHC Lighting & BMS Sp. z o.o. ',
    '072B': 'NEWSUBSTANCE Ltd.  ',
    '072C': 'SGM A/S ',
    '072F': 'RayComposer - R. Adams ',
    '0732': 'Galaxia Electronics ',
    '0734': 'CPOINT ',
    '073B': 'Corsair Technology Ltd. ',
    '0740': 'Arkalumen ',
    '0745': 'Guangzhou Wingo Stage Light Co., Ltd ',
    '074F': 'Panasonic Corporation ',
    '0753': 'F&V Europe B.V. ',
    '0758': 'IMPOLUX GmbH ',
    '075F': 'LEDEngin Inc. ',
    '076A': 'BeamZ (Tronios B.V.) ',
    '0776': 'lumenetix ',
    '078A': 'FATEC sarl ',
    '0792': 'MY-Semi Inc. ',
    '07A3': 'Guangzhou GBR PROLIGHT GROUP CO.,LTD (GBR PROLIGHT) ',
    '07A5': 'X LED Systems ',
    '07AD': 'CLS LED BV ',
    '07AE': 'A-LITE B.V. ',
    '07B0': 'ADDiCTiON BoX GbR ',
    '07B1': 'TBF-PyroTec GmbH  ',
    '07B3': 'Shenzhen Fabulux Technology Co., Ltd ',
    '07B5': 'ARM Automation, Inc ',
    '07BE': 'Sanko Device Co.Ltd. ',
    '07C0': 'Code Mercenaries GmbH ',
    '07C2': 'BOOQlight BV ',
    '07C8': 'Sidus Link Ltd. ',
    '07CC': 'Griven S.r.l. ',
    '07CF': 'MH-Sound ',
    '07D1': 'Made By Mouse LTD ',
    '07D5': 'PHIDA Stage Equipment Co., Ltd ',
    '07D6': 'Lite Puter Enterprise Co., Ltd. ',
    '07DA': 'Flytech s.r.l. ',
    '07E8': 'ROCKETSIGN Technology HK Ltd ',
    '07E9': 'TechLink Co., Ltd. ',
    '07EA': 'Le Maitre Ltd ',
    '07F3': 'Sam Light ',
    '07F4': 'LED Flex Ltd. ',
    '07F5': 'Shenzhen ATENTI Technologies Co., Ltd ',
    '07F6': 'Electric Distribution Systems ',
    '07F7': 'Dakco Technologies Co., Ltd. ',
    '07F8': 'Ultimate Technology Solutions GmbH ',
    '07FD': 'THELIGHT Luminary for Cine and TV S.L. ',
    '07FF': 'Guangzhou HOMEI LIGHT Manufacturer ',
    '0800': 'Hongyeah Light ',
    '0801': 'Guangzhou Favolite Stage Lighting Co., Ltd. ',
    '0802': 'AstralPool ',
    '0807': 'Event Lighting Pty, Ltd. ',
    '0808': 'Cooper Lighting - Zero 88 ',
    '0809': 'mumoco GmbH ',
    '080A': 'Shenzhen FantaLED Electronics Co., Ltd ',
    '080D': 'HBJ Elektronik ',
    '080F': 'NavoLabs ',
    '0810': 'BDS Studios ',
    '0811': 'V-PRO ',
    '0812': 'Yamagiwa Corporation ',
    '0823': 'Opito Labs GmbH ',
    '0824': 'Almotechnos CO.,LTD. ',
    '0832': 'Shenzhen EXC-LED Technology Co.,Ltd ',
    '083A': 'Bright Ideas Custom Electronics Inc. ',
    '083E': 'Guangdong Hua Chen Film & Television Stage Project Co., Ltd. ',
    '083F': 'Shenzhen LeiFei Lighting Technologies Co.,Ltd. ',
    '0840': 'Shenzhen Zwich Science and Technology Co.Ltd. ',
    '0845': 'Cush Light LLC ',
    '0846': 'LDR - Luci della Ribalta Srl ',
    '084B': 'Neon Circus Ltd ',
    '084C': 'Guangzhou Ba Lin Electronic Technology Co., Ltd. ',
    '084D': 'Guangzhou NECO Stage Lighting Factory ',
    '0850': 'Proland Group, LLC ',
    '0851': 'Junction Inc. Ltd ',
    '0854': 'NEC Display Solutions, Ltd. ',
    '0854': 'Sharp NEC Display Solutions, Ltd. ',
    '0855': 'GODOX Photo Equipment Co., Ltd. ',
    '0858': 'Juno Lighting Group  ',
    '085A': 'Guangzhou Ming Jing Stage Light Equipment Co., Ltd. ',
    '085E': 'MMS Distribution Ltd ',
    '085F': 'Media Visions, Inc. ',
    '0863': 'XTEC Industries Pte Ltd ',
    '0865': 'Contrade GmbH ',
    '0868': 'Ushio America, Inc. ',
    '0869': 'Club Cannon LLC ',
    '086C': 'Bafa Elektronik ve Işık Tasarımları Sanayii Ticaret LTD Sti. ',
    '086E': 'Guangzhou Hi-LTTE Electronics Technology Co.,Ltd  ',
    '0870': 'Hunan YESTECH Optoelectronic Co., Ltd ',
    '0873': 'Guangzhou BKLite Stage Lighting Equipment Co.,LTD ',
    '0874': 'Snow Professional Lighting ',
    '0875': 'ARC Solid-State Lighting Corp. ',
    '0876': 'Power Gems LTD ',
    '0878': 'OTTEC Technology GmbH ',
    '087D': 'TPV Technology Group ',
    '0880': 'GuangZhou LiDang Technology Inc. ',
    '0883': 'CEE Lighting Equipment Co.Ltd ',
    '0884': 'Bright Group ',
    '0885': 'SIRS-E ',
    '0886': 'KLIK Systems ',
    '0889': 'Guangzhou Shenghui Electronic Technology Co., Ltd ',
    '088A': 'Highendled Electronics Company Limited ',
    '088B': 'Shenzhen Doit Vision Co., Ltd ',
    '088D': 'Guangzhou Ling Yang lighting Science and Technology Co.,Ltd ',
    '088E': 'Stage One International Co., Ltd.  ',
    '088F': 'First Design System Inc. ',
    '0890': 'Taurus Light Co.,Limited ',
    '0891': 'Feiner Lichttechnik GMBH ',
    '0892': 'DongGuan Ruishen Technology Co.,Ltd ',
    '0893': 'Brighten LED Lighting Limited ',
    '0894': 'Dongguan HCP Technology Co., Ltd. ',
    '089A': 'ADL Electronics Ltd. ',
    '089D': 'gobo.ws ',
    '08A1': 'Shenzhen Gloshine Technology Co., Ltd ',
    '08A2': 'Guangzhou Gesida Light Equipment Co., Ltd. ',
    '08A3': 'Redot Visual Effect Technologies (Shenzhen) Co., Ltd ',
    '08A4': 'Adam Hall GmbH ',
    '08A7': 'GuangZhou Deliya Opto-electronic Tech Co., Ltd ',
    '08AA': 'PiXL Factory ',
    '08AB': 'Qdot Lighting Limited  ',
    '08AC': 'Bushveld Labs ',
    '08AD': 'Optical Productions LLC ',
    '08AE': 'Technical Audio Group Pty Ltd ',
    '08AF': 'AAdyn Technology ',
    '08B0': 'KIM Lighting ',
    '08B2': 'MCI Group ',
    '08B3': 'Stealth Light srl ',
    '08B6': 'Graf Lichttechnik UG ',
    '08B9': 'Guangzhou Hua Rong Electronic Technology Co., Ltd. ',
    '08BA': 'Meteor Lighting ',
    '08BB': 'Guangzhou CHEN Electronic Technology Co., Ltd. ',
    '08BC': 'Michael Parkin ',
    '08BD': 'Lug Light Factory Sp. z o. o. ',
    '08BF': 'Times Square Stage Lighting Inc. ',
    '08C1': 'Project SSSHH Incorporated ',
    '08C3': 'Guangzhou Spark Stage Equipment Co. Ltd ',
    '08C5': 'EHRGEIZ Lichttechnik GmbH ',
    '08C9': 'LEDitgo Videowall Germany GmbH ',
    '08CA': 'Foshan City Xuandao Optoelectronics Equipment Co., Ltd ',
    '08CC': 'Guangzhou Santu Stage Lighting Equipment Co.Ltd ',
    '08D3': 'SVI Public Company Limited  ',
    '08D4': 'Sensa-Lite Ltd. ',
    '08D5': 'Sense Effects ',
    '08D6': 'Guangzhou Precision Vision Intelligent Equipment Co, Ltd ',
    '08D7': 'PatternAgents, LLC ',
    '08D8': 'W.A. Benjamin Electric Co. ',
    '08D9': 'STILED ',
    '08DA': 'PLC Intelligent Technology (Shanghai) Co., Ltd. ',
    '08DD': 'Matthew Tong ',
    '08E0': 'Red Arrow Controls ',
    '08E1': 'Shenzhen CLT Electronics Co.,LTD  ',
    '08E3': 'Guangzhou JinZhiHui Electronic Technology Co.,Ltd. ',
    '08E4': 'LMP Lichttechnik Vertriebsgesellschaft GmbH & Co KG ',
    '08E7': '3A Guangzhou Electronics Co., Ltd ',
    '08EC': 'Marvin Nadrowski ',
    '08ED': 'ShowLED ',
    '08EE': 'Spacelights ',
    '08EF': 'Guangzhou RuiYang lighting technology co. LTD. ',
    '08F0': 'Guang Dong LMJ Lighting Co., Ltd ',
    '08F1': 'SanDevices, LLC ',
    '08F3': 'Outdoor Lasers Ltd. ',
    '08F4': 'MC Electronic Technology(GZ) Co., Ltd. ',
    '08F6': 'Eulum Design, LLC ',
    '08F7': 'Neotek Lighting ',
    '08F8': 'Liberal Logic Inc. ',
    '08F9': 'ACS - Ackerman Computer Sciences ',
    '08FA': 'Phaton Lighting Co., Ltd. ',
    '08FC': 'Lights By Brian ',
    '08FE': 'Zhuhai Shengchang Electronics Co., Ltd. ',
    '0900': 'nox multimedia GmbH ',
    '0901': 'GermTec GmbH & Co. KG ',
    '0902': 'DongGuan Betterway Lighting Co.,Ltd ',
    '0903': 'Shenzhen INFiLED Electronics, Ltd. ',
    '0904': 'Bigbear Co., Ltd. ',
    '0905': 'Locimation Pty Ltd ',
    '0906': 'Crystal Technica Limited ',
    '0909': 'Beijing Starlight Electronics Co., Ltd. ',
    '090B': 'StarLighting ',
    '090C': 'GRE Alpha ',
    '090E': 'Sichuan esRadio Technology Co., Ltd ',
    '0910': 'Shenzhen Tecnon EXCO-Vision Technology Co., Ltd. ',
    '0911': 'Guangzhou Aceda Professional Lighting Co., Ltd. ',
    '0912': 'ags - Wissenschaftliche Arbeitsgemeinschaft fur Studio- und Senderfragen ',
    '0913': 'Guangzhou ECK Light Equipment Company Limited ',
    '0914': 'Xenio ',
    '0915': 'Guangzhou Chuangfeng Photoelectric Equipment Co., Ltd. ',
    '0916': 'ACTOR-MATE CO., LTD. ',
    '0918': 'David O Smith Design ',
    '0919': 'Foshan Leiyuan Photoelectric Co., LTD ',
    '091A': 'Celex LED Technology Ltd. ',
    '091B': 'Krislite Pte. Ltd. ',
    '091D': 'TouchPlate Technologies Inc. ',
    '0920': 'Vexica Technology Limited ',
    '0921': 'Guangzhou mengyi stage lighting equipment co., LTD. ',
    '0923': 'Hangzhou Roleds Lighting System Co., Ltd. ',
    '0925': 'Guangzhou Aiweidy Lighting Acoustics Equipment Co.,Ltd. ',
    '0926': 'Elumeros Lighting Limited  ',
    '0927': 'Guangzhou Mingying Electronic Technology Co., Ltd. ',
    '0929': 'UPlight stage equipment(GZ) CO., Ltd. ',
    '092B': 'Guangzhou Lightful Stage Lighting&Sound Equipment Co,.Ltd. ',
    '092C': 'Guangzhou Chaoran Computer Co., Ltd. ',
    '092F': 'Guangzhou Shinelight Stage Equipment Factory  ',
    '0930': 'jiaozuo shengguang film &equipment Co. Ltd ',
    '0931': 'Cristal Controles ',
    '0935': 'Guangzhou Huadu District Richa Lighting Equipment Factory ',
    '0936': 'AquaTronic ',
    '0937': 'Huizhou Zhonghan Electronic Technology Co., Ltd ',
    '0938': 'Guangzhou Vanray Lighting Equipment CO.,Ltd. ',
    '0939': 'Edelmann Electronics ',
    '093A': 'HDT impex s.r.o. ',
    '093B': 'Guangzhou Hongmingwei Stage Lighting Co., Ltd. ',
    '093D': 'Sichuan Hushan Electric Co. Ltd ',
    '093F': 'Guangzhou Julong Platform Lighting Equipment Factory ',
    '0940': 'Shenzhen CreateLED Electronics Co., Ltd ',
    '0941': 'Shenzen Zhuoyang Intelligent Technology Co., Ltd. ',
    '0945': 'Guangzhou Lin Xiang Stage Lighting Equipment CO.,LTD ',
    '0946': 'TBE Srl ',
    '0948': 'Wisconsin Lighting Lab, Inc. (WiLL) ',
    '094A': 'Funovation, Inc ',
    '094B': 'Invisua Lighting BV ',
    '0951': 'Guangzhou GTD Lighting Technology Co., Ltd  ',
    '0952': 'Guangzhou Sunway Entertainment Equipment Co., Ltd. ',
    '0958': 'Illum Technology LLC (previously Verde Designs, Inc.) ',
    '0959': 'Urbs Lighting, LLC ',
    '095A': 'kLabs Research UK ',
    '095B': 'Wuhan Zhongtian Jiaye Mechanical and Electrical Engineering Co. LTD ',
    '095F': 'Elaborated Networks GmbH ',
    '0960': 'Fineline Solutions Ltd. ',
    '0965': 'Fontana Fountains ',
    '0967': 'Arcus Licht- und Praesentationstechnik GmbH ',
    '0968': 'Guangzhou Beyond Lighting Co., Limited.  ',
    '096D': 'Guangzhou Xin Yilong Stage Lighting Equipment Co., Limited ',
    '096F': 'Shenzhen showho technolgy co.,ltd  ',
    '0973': 'Guangzhou Eagle Wei Photoelectric Technology Co., Ltd. ',
    '0974': 'Marumo Electric Co., Ltd. ',
    '0975': 'KB Design ',
    '0977': 'Guangzhou HuaYong Intelligent Technology Co., Ltd. ',
    '097A': 'Teamboyce Limited ',
    '097D': 'Brink Electronics ',
    '097E': 'Guangzhou Deyi Lighting Co., Ltd. ',
    '097F': 'RaumZeitLabor e.V. ',
    '0980': 'Moog Animatics ',
    '0981': 'Luxam, Ltd. ',
    '0982': 'AC Entertainment Products Ltd. ',
    '0986': 'ROE Visual Co. Ltd. ',
    '0987': 'mathertel.de ',
    '0989': 'YeGrin Liteworks ',
    '098B': 'Glow Motion Technologies, LLC. ',
    '098C': 'Shenzhen Longrich Energy Sources Technology Co., Ltd.  ',
    '098D': 'Batmink Ltd. ',
    '098E': 'Ecosense Lighting Inc ',
    '098F': 'Digital Sputnik Lighting ',
    '0990': 'Stagelight Holding ',
    '0996': 'CCI Power Supplies, LLC ',
    '0997': 'Star Iluminacao Computadorizada LTDA ',
    '099A': 'Aixz International (S) ',
    '099E': 'LLC Lighting Technologies production ',
    '09A0': 'Rnet Lighting Technology Limited ',
    '09A2': 'Fountain People ',
    '09A3': 'Shenzhen Lightlink Display Technology Co., Ltd ',
    '09A5': 'Prolight Concepts Ltd. ',
    '09AE': 'Robert Juliat ',
    '09AF': 'Autotech Co. ',
    '09B2': 'Guangzhou Hedong Electronics Co., LTD ',
    '09B3': 'Aquatique Show Int. ',
    '09B4': 'Brompton Technology Ltd. ',
    '09B5': 'XBlack Visual Products ',
    '09B7': 'inCon-trol water systems ',
    '09B8': 'Prolites S.A.L. ',
    '09BD': 'Shenzhen Zhongbo Photoelectric Co., Ltd ',
    '09C0': 'Guangzhou Rainbow Lighting Equipment CO.,LTD ',
    '09C1': 'Argetron Elektrik Elektronik Organizasyon Gida San. ve Dis Tic. Ltd. Sti. ',
    '09C3': 'Velleman nv ',
    '09C4': 'Guangzhou XinHuang Industrial Co., Ltd. ',
    '09C6': 'Photon Manufacturing ',
    '09C8': 'Crystal Fountains Inc. ',
    '09CC': 'Motomuto Aps ',
    '09D1': 'Environmental Lights ',
    '09D3': 'WLPS Wodielite Production Services ',
    '09D4': 'Guangzhou Yilaiming Photoelectric Technology Co., Ltd ',
    '09D6': 'Mittomakers ',
    '09D7': 'Unilumin Group ',
    '09DE': 'Matthias Bauch Software ',
    '09E9': 'Starway ',
    '09EE': 'Suzhou Pinzong Electronic Technology, CO.,Ltd ',
    '09F8': 'UberDisplays ',
    '09FC': 'deskontrol electronics ',
    '0A01': 'Star-Reach Corporation ',
    '0AAA': 'AAA-LUX ',
    '1112': 'Zhuhai Bincolor Electronic Technology Co., Ltd. ',
    '1113': 'SiliconCore Technology, Inc. ',
    '1200': 'Seekway Technology Limited ',
    '1201': 'PRICOM Design ',
    '1202': 'Ushio Lighting, Inc. ',
    '1203': 'Movecat GmbH ',
    '1204': 'ARES s.r.l. - Socio Unico ',
    '1205': 'Carbon Lighting Limited ',
    '1206': 'Hangel Technology Co., Ltd. ',
    '1208': 'Nuvolight GmbH & Co KG ',
    '1209': 'Philippe Bergeron Lights ',
    '120A': 'Bulldog Lighting and Events, Inc. ',
    '120B': 'Brilliant Stages Ltd. ',
    '1212': 'HPL Light Company ',
    '1221': 'SAGITTER - Proel ',
    '1222': 'SM International ',
    '1234': 'ESTA ',
    '12DA': 'Newlab S.r.l. ',
    '12E0': 'Luxlight Skandinavien AB ',
    '12EA': 'Kolberg Percussion GmbH ',
    '12F4': 'Stage Services Ltd. ',
    '12FA': 'Hollywood Rentals LLC ',
    '12FE': 'City Design S.p.A. ',
    '131E': 'Blossom Communications Corp. ',
    '1337': 'Raven Systems Design, Inc. ',
    '134D': 'VT-Control ',
    '1370': 'Ingenieurbuero Stahlkopf ',
    '13AE': 'Smartpark Creative Solutions ',
    '1460': 'SEIKO Epson Corporation ',
    '1464': 'HUMAL Elektroonika OU ',
    '1490': 'Grid Show Systems Inc. ',
    '14A0': 'Intense Lighting, LLC ',
    '14AC': 'Zaklad Elektroniczny AGAT s.c. ',
    '1506': 'v2 Lighting Group, Inc. ',
    '150C': 'ACASS SYSTEMS LLC ',
    '152A': 'SHOWTACLE Ltd. ',
    '154E': 'Fire & Magic ',
    '15A0': 'GuangZhou MCSWE Technologies, INC  ',
    '15A2': 'FEIMEX ',
    '15D0': 'Music & Lights S.r.l. ',
    '161A': 'techKnow Design Ltd. ',
    '1626': 'LEDsistem Teknolojileri Tic. Ltd. Sti. ',
    '1627': 'Dynamic Visual Solutions LLC ',
    '162A': "Nerd's Meter ",
    '1690': 'awaptec GmbH ',
    '16AE': 'Electrone Americas Ltd. Co. ',
    '16DC': 'Traxon Technologies Ltd.  ',
    '16E4': 'Aboutshow Color Light Co., LTD ',
    '16FA': 'Lite Puter Enterprise Co., Ltd. ',
    '1701': 'ARTBOX ',
    '170E': 'Serva Transport Systems GmbH ',
    '170F': 'Kezun Stage Lighting Equipment Co., Ltd. ',
    '174E': 'Nordgas SNe-lightingsystem ',
    '1750': 'Yuesheng International Limited ',
    '1808': 'Guangzhou Jinye Electronic Technology Co., Ltd. ',
    '1809': 'Rotolight ',
    '180A': 'Guangdong Longjoin Optoelectronics Technology Co. Ltd. ',
    '1871': 'Smoke Factory GmbH ',
    '1872': 'Super-Can Industry Growing Co. Ltd. ',
    '1873': 'Zhongshan Wellmake Electronic Technology Co., Ltd. ',
    '1888': 'GUANZHOU KAVON STAGE EQUIPMENT CO., LTD. ',
    '18A6': 'Steadfast Technology ',
    '1900': 'ADJ Products LLC ',
    '1938': 'Solid State Luminaires ',
    '1998': 'PLS Electronics Ltd. ',
    '19B9': 'Duralamp S.p.A. ',
    '19BA': 'Guangzhou Xinzhijie Photoelectric Co., Ltd. ',
    '19BB': 'Panalux Ltd. ',
    '19F8': 'CEZOS Spolka z ograniczona odpowiedzialnoscia, sp.k. ',
    '1A00': 'LIGEO GmbH ',
    '1A0D': 'Cineo Lighting ',
    '1A16': 'WADAK GmbH ',
    '1A1A': 'ValDim Waterfountains Ltd. ',
    '1A3D': 'Red Lighting s.r.l. ',
    '1AFA': 'TMB ',
    '1BB1': 'PH Lightning AB ',
    '1BC0': 'ALS Stanislaw Binkiewicz ',
    '1BC6': 'Studio S Music City ',
    '1C80': 'Vehtec Tecnologia Ltda ',
    '1E8D': 'Moda Light ',
    '1ECF': 'Masiero s.r.l. ',
    '1ED8': 'Antari Lighting And Effects Ltd. ',
    '2009': 'Zboxes Intelligent Technology (Shanghai) Co., Ltd.  ',
    '200A': 'Vault189 Pty. Ltd. ',
    '2011': 'Gantom Lighting & Controls ',
    '207F': 'Padura Elektronik GmbH ',
    '20A6': 'ALADIN Architekturlicht GmbH ',
    '20AD': 'AZ e-lite Pte Ltd ',
    '20B6': 'Alkalite LED Technology Corp ',
    '20B8': 'Electron SA ',
    '20B9': 'ARRI -- Arnold & Richter Cine Technik GmbH & Co. Betriebs KG ',
    '20BA': 'AusChristmasLighting ',
    '20BB': 'Able Laser Tech Co., Ltd.  ',
    '20BC': 'Beijing Pargolite Technology Co., Ltd. ',
    '20BD': 'Foshan Yoline Lighting Equipment Co., Ltd. ',
    '20BE': 'Uranus Lighting Co., Ltd. ',
    '20BF': 'Guangzhou Taifeng Stage Lighting Audio Equipment Factory ',
    '20C0': 'KappaStyle Productions. ',
    '20C1': 'BrightBeats, LLC ',
    '20C2': 'Demilight ',
    '2121': 'Brother,Brother & Sons Aps ',
    '2122': 'BEGLEC NV ',
    '2130': 'Bart van Stiphout Electronics & Software ',
    '21A1': 'Culture Crew bvba ',
    '21A4': 'CHAUVET Lighting ',
    '21A9': 'CaptSystemes ',
    '21B3': 'Coolon Pty Ltd ',
    '21B4': 'CHROMLECH ',
    '21B5': 'ChromaCove LLC ',
    '2208': 'C.I.M.E.S. (Conception Installation Maintenance En Eclairage & Sonorisation) ',
    '2216': 'D-Light Designs, LLC ',
    '2222': 'D.E.F. Srl ',
    '2224': 'DAS Integrator Pte Ltd ',
    '2239': 'Dream Solutions Ltd. ',
    '22A0': 'EAS SYSTEMS ',
    '22A6': 'Elation Lighting Inc. ',
    '22A9': 'Engineering Solutions Inc. ',
    '22AA': 'EUTRAC - Intelligent Lighting GmbH ',
    '22AB': 'EVC ',
    '22B9': 'Etherlight ',
    '2337': 'Focon Showtechnic ',
    '23B2': 'Gekko Technology Ltd. ',
    '2421': 'HB-Laserkomponenten GmbH ',
    '242A': 'Hungaroflash ',
    '2432': 'Helvar Ltd ',
    '2470': 'Hale Microsystems LLC ',
    '24A3': 'Lighting Innovation Group AG ',
    '24AA': 'IT Ihme ',
    '2621': 'LEADER LIGHT s.r.o. ',
    '2622': 'LDDE Vertriebs Gmbh ',
    '2623': 'Leonh Hardware Enterprise Inc. ',
    '2624': 'Lisys Fenyrendszer Zrt. ',
    '2626': 'LLT Lichttechnik GmbH&CO.KG ',
    '2630': 'Laservision ',
    '2632': 'Lehigh Electric Products ',
    '2635': 'LjusDesign AB ',
    '2636': 'Lumonic Limited ',
    '2637': 'Loxone Electronics GmbH ',
    '263A': 'Lumenec Pty. Ltd. ',
    '263C': 'I-Pix Digital Light Ltd. ',
    '26A2': 'MEGATECHNICS Ltd. ',
    '26B4': 'Milford Instruments Ltd. ',
    '2724': 'Nila Inc. ',
    '2734': 'Nixer Ltd. ',
    '27A8': 'Callegenix LLC ',
    '2821': 'Pioneer Corporation ',
    '2826': 'Peter Maes Technology ',
    '2827': 'Peternet Electronics BVBA  ',
    '2829': 'PR-Electronic ',
    '2836': 'Planungsbuero ',
    '28E1': 'MTC maintronic GmbH ',
    '2927': 'ROAL Electronics SpA ',
    '297E': 'Lifetime Music Academy ',
    '2984': 'Getlux Ltd. ',
    '2999': 'ALL-DO INTERNATIONAL CO., LTD. ',
    '29A1': 'Sturdy Corporation ',
    '29A9': 'SRS Light Design ',
    '29AA': 'Steinigke Showtechnic GmbH ',
    '29B2': 'Selectron Bvba ',
    '29B4': 'Showtec (Highlite International B.V.) ',
    '29B7': 'Sundrax, LLC ',
    '29B8': 'Spotlight s.r.l. ',
    '29BA': 'State Automation Pty Ltd. ',
    '29E8': 'Stroytsirk LLC ',
    '2A25': 'Thorn Lighting Limited ',
    '2A26': 'Toni Maroni Gmb ',
    '2AAB': 'Urban Visuals & Effects Ltd. ',
    '2B28': 'Visual Productions ',
    '2B29': 'MaNima Technologies BV ',
    '2BA2': 'WERPAX bvba ',
    '2BA9': 'The White Rabbit Company, Inc. ',
    '2BB4': 'Williams Electronic Design Ltd. ',
    '2C1A': 'DMX4ALL GmbH ',
    '2C2A': 'XTBA ',
    '2CE0': 'Lighting Services Inc. ',
    '2DC8': 'Stellascapes ',
    '2DDD': 'Waylight ',
    '2DDE': 'Luminlite Electronics Co., Ltd. ',
    '3000': 'PushingPixels ',
    '3001': 'Elemental LED, Inc. ',
    '3002': 'Siberian Lighting ',
    '3003': 'ChamSix ',
    '3235': 'de koster Special Effects ',
    '3331': 'DMG Lumiere ',
    '3332': 'Teclumen s.r.l. ',
    '3333': 'NightStarry Electronics Co., LTD. ',
    '3388': 'Macostar International Ltd. ',
    '3434': 'Global Design Solutions, Ltd. ',
    '3534': 'Five4, LLC ',
    '3535': 'Changsha Spark Technology Electronics Ltd. ',
    '3536': 'Cindy Professional Lighting Co., Ltd.  ',
    '3537': 'Novacorp Inc. ',
    '361D': 'Lumishore Ltd. UK ',
    '3638': 'Lumenpulse Lighting Inc. ',
    '37D0': 'Boogy Brothers Showequipment ',
    '37D7': 'Lichttechnik & Sonderbau ',
    '3805': 'Yifeng Lighting Co., Ltd. ',
    '3806': 'ACME EFFECTS LTD. ',
    '3868': 'LanBolight Technology Co., LTD. ',
    '3888': 'Fly Dragon Lighting Equipment Co.,ltd ',
    '388A': 'Guangzhou Yajiang (Yagang - Silver Star) Photoelectric Equipment Ltd. ',
    '3A37': 'TheOlymp - Networking & InterNet Services ',
    '3AFC': 'Black Tank Engineering ',
    '3B10': 'NXP Semiconductors B.V. ',
    '3B88': 'Shenzhen Eastar Electronic Co., Ltd. ',
    '3D30': 'zactrack Lighting Technologies Gmbh ',
    '400D': 'Quasar Science LLC ',
    '4051': 'SAN JACK ANALOG HOUSE CO., LTD. ',
    '4131': 'Altman Stage Lighting ',
    '4141': 'AVAB America, Inc. ',
    '4142': 'Filmgear, Inc. ',
    '4143': 'AC Lasers ',
    '4144': 'ADB - TTV Technologies nv ',
    '4145': 'ADE ELETTRONICA srl  ',
    '4146': 'AUS FX ',
    '4149': 'Anidea Engineering, Inc. ',
    '414C': 'Artistic Licence Engineering Ltd. ',
    '414D': 'Amptown Lichttechnik GmbH ',
    '414E': 'Anytronics Ltd. ',
    '4150': 'Apogee Lighting ',
    '4151': 'Aquarii, Inc. ',
    '4153': 'Audio Scene ',
    '4154': 'Arnold Tang Productions ',
    '4156': 'Audio Visual Devices P/L ',
    '4164': 'Adelto Industries Ltd. ',
    '416C': 'Alenco BV ',
    '4172': 'ARNOLD LICHTTECHNIK ',
    '4173': 'Astera LED Technology GmbH ',
    '4179': 'AYRTON ',
    '4241': 'BECKHOFF Automation GmbH ',
    '4243': 'Bill Coghill Company : Bill Coghill Design ',
    '4245': 'Bytecraft Entertainment Pty Ltd ',
    '424F': 'BOTEX ',
    '4253': 'Barco ',
    '42A2': 'Birket Engineering, Inc. ',
    '4321': 'Design Partners of Canada ',
    '4344': 'CDCA Ltd. ',
    '4347': 'CAST Software ',
    '4349': 'C.I.Tronics Lighting Designers Ltda ',
    '434B': 'Color Kinetics Inc. ',
    '434C': 'Crealux GmbH & Co. KG ',
    '434D': 'Coemar Spa ',
    '434F': 'Cortex Design ',
    '4350': 'CLAY PAKY S.p.A ',
    '4353': 'Capricorn Software ',
    '4354': 'City Theatrical, Inc. ',
    '4358': 'Connex GmbH ',
    '4369': 'Cinetix Medien u. Interface GmbH ',
    '436F': 'CODEM MUSIC S.r.l. ',
    '4441': 'DIGITAL ART SYSTEM ',
    '4442': 'ELETTROLAB S.r.l. ',
    '4443': 'Claudio Dal Cero Engineering ',
    '4444': 'D.O.M. Datenverarbeitung GmbH ',
    '4445': 'Dezelectric Kft. ',
    '4446': 'Doug Fleenor Design, Inc. ',
    '4449': 'Durand Interstellar, Inc. ',
    '444C': 'Dove Lighting Systems, Inc. ',
    '444D': 'Digimedia Multimedia Lighting Solutions ',
    '444E': 'DALCNET SRL ',
    '4450': 'DMXPROFI.EU GmbH i.G. ',
    '4453': 'Guangzhou Desheng Lighting Industrial Co., Ltd. ',
    '4456': 'Devantech Ltd. ',
    '4466': 'DF elettronica s.r.l. ',
    '4469': 'Diamante Lighting Srl ',
    '446C': 'Guangdong Delos Lighting Industrial Co.,Ltd. ',
    '453A': 'E:cue Control GmbH ',
    '4541': 'Engineering Arts ',
    '4543': 'EC Elettronica Srl ',
    '4544': 'Electronics Diversified LLC ',
    '4545': 'EastSun Technology Co. Ltd. ',
    '454C': 'Ingenieurbuero fuer Nachrichtentechnik in der Studio und Veranstaltungstechnik ',
    '454D': 'ELM Video Technology, Inc. ',
    '454E': 'ENTTEC Pty Ltd ',
    '4552': 'EREA ',
    '4553': 'ERAL srl ',
    '4554': 'Entertainment Technology ',
    '4563': 'Les Eclairages Lou Inc. ',
    '456C': 'Element Labs Inc. ',
    '4631': 'OKEROAB AB ',
    '464C': 'Flashlight/Ampco Holding ',
    '4656': 'Flexvisual ',
    '4658': 'MAGIC FX B.V. ',
    '4678': 'Global Special Effects ',
    '4744': 'Goddard Design Co. ',
    '4745': 'GPE srl ',
    '4747': 'G&G LED Lighting ',
    '474C': 'G-LEC Europe GmbH ',
    '4750': 'DES ',
    '4753': 'Guangzhou Haoyang Electronic Co., Ltd. ',
    '476C': 'General Luminaire (Shanghai) Ltd. ',
    '4800': 'VOD VISUAL.CO. (UK) Ltd. ',
    '4801': 'Capture Visualisation AB ',
    '4843': 'Horizon Control Inc. ',
    '4844': 'HxDx ',
    '4845': 'Howard Eaton Lighting Ltd. ',
    '484C': 'HBE Lighting Systems ',
    '484F': 'Hollywood Controls Inc. ',
    '4856': 'Enfis Ltd ',
    '4881': 'Rena Electronica B.V. ',
    '4941': 'inoage GmbH ',
    '4942': 'IBEX UK Limited ',
    '4944': 'Ingham Designs ',
    '4945': 'Insta Elektro GmbH ',
    '4947': 'IGuzzini illuminazione spa ',
    '4948': 'Ice House Productions ',
    '494C': 'I-Lum ',
    '494E': 'Interactive Technologies, Inc. ',
    '4950': 'Interesting Products, Inc. ',
    '4951': 'IQAir AG ',
    '4952': 'Invisible Rival Incorporated ',
    '4953': 'Integrated System Technologies Ltd. ',
    '4954': 'Integrated Theatre, Inc. ',
    '4973': 'Innovation Solutions Ltd. ',
    '4A31': 'Joshua 1 Systems Inc. ',
    '4A41': 'JANUS srl ',
    '4A42': 'JB-lighting GmbH ',
    '4A48': 'James Harris ',
    '4A4C': 'Johnsson Lighting Technologies AB ',
    '4A53': "JSC 'MFG' ",
    '4A54': 'James Thomas Engineering ',
    '4A61': 'Jands Pty Ltd. ',
    '4ACC': 'RVL techniek ',
    '4B42': 'KissBox ',
    '4B46': 'Kino Flo, Inc. ',
    '4B4C': 'KLH Electronics PLC ',
    '4B4D': 'KMX Inc. ',
    '4B55': 'kuwatec, Inc. ',
    '4C20': 'LAM32 srl ',
    '4C41': 'LaserAnimation Sollinger GmbH ',
    '4C44': 'LVDIAN PHOTOELECTRIC SCIENCE TECHNOLOGY LIMITED ',
    '4C45': 'Leviton Manufacturing Co., Inc. ',
    '4C47': 'LightGeist Ltd. ',
    '4C4C': 'LUMINEX Lighting Control Equipment bvba ',
    '4C4D': 'Ultratec Special Effects ',
    '4C50': 'LightProcessor Ltd ',
    '4C52': 'High End Systems Inc. ',
    '4C53': 'Licht-, Steuer- und Schaltanlagenbau GmbH (LSS GmbH) ',
    '4C54': 'Licht-Technik ',
    '4C55': 'LumenRadio AB ',
    '4C56': 'LEDValley Technologies Sdn Bhd ',
    '4C57': 'LightWild LC ',
    '4C58': 'Lex Products Corp. ',
    '4C59': 'Laser Technology Ltd. ',
    '4C5A': 'LightMinded Industries, Inc. ',
    '4C5A': 'Sumolight GmbH ',
    '4C5B': 'LightLife, Gesellschaft fur audiovisuelle Erlebnisse mbH ',
    '4C64': 'LED Team ',
    '4C65': 'Legargeant and Associates ',
    '4C69': 'LIGHTOLIER ',
    '4C6C': 'Lampo Lighting Designers ',
    '4C73': 'LSC Lighting Systems (Aust) Pty. Ltd. ',
    '4CDC': 'acdc LED Ltd. ',
    '4CE5': 'LED Company s.r.o. ',
    '4D41': 'MA Lighting Technology GmbH ',
    '4D42': 'LAN Systems--Midibox project ',
    '4D44': 'Les Generateurs de brouillard MDG Fog Generators Ltd. ',
    '4D4C': 'Mode Lighting (UK) Ltd. ',
    '4D50': 'Martin Professional A/S ',
    '4D54': 'medien technik cords ',
    '4D56': 'Avolites Ltd. ',
    '4D58': 'MX design ',
    '4D5A': 'Covert Science GmbH ',
    '4D61': 'MARTINI S.p.A. ',
    '4D77': 'Mueller Elektronik ',
    '4E41': 'Company NA ',
    '4E4A': 'NJD Electronics ',
    '4E4C': 'NOVALIGHT S.r.l. ',
    '4E57': 'AIM Northwest ',
    '4E69': 'Niko ',
    '4F41': 'Oase GmbH ',
    '4F43': 'Offstage Controls (formerly Obsidian Control) ',
    '4F4C': 'DDS Elettronica ',
    '4F75': 'Outsight Pty Ltd. ',
    '5000': 'http://www.orangepi-dmx.org ',
    '5001': 'Hua Yuan Ke Tai ',
    '5002': 'Shanghai Shylon Optoelectronic Technology Co., Ltd. ',
    '5003': 'Futlight Optoelectronics Co.,Ltd. ',
    '5004': 'Shanghai Sansi Electronic Engineering Co.,Ltd ',
    '5005': 'MEDIAM Ltd. (Modus brand) ',
    '5006': 'ENEDO Power SpA ',
    '5007': 'Alfalite ',
    '5008': 'Chengdu Chengyu Electronic Technology Co., Ltd. ',
    '5009': 'Izzro Optoelectronics Technology Co., Ltd. ',
    '500A': 'AU Optronics Corporation (AUO) ',
    '500B': "WebKat Eletronic's ",
    '5040': 'Guangzhou Color Imagination LED Lighting Ltd. ',
    '5041': 'Philips Entertainment Lighting Asia ',
    '5043': 'Pathway Connectivity Inc. ',
    '504C': 'Peperoni Lighting-Solutions ',
    '504D': 'Peter Meyer Project Management Adviser GmbH ',
    '5050': 'Newton Engineering and Design Group LLC ',
    '5051': 'PDQ Manufacturing, Inc ',
    '5052': 'Production Resource Group ',
    '5053': 'Philips Selecon ',
    '5058': 'PXM s.c. ',
    '5062': 'LED, Inc. ',
    '5065': 'Peradise ',
    '5066': 'Pfannenberg GmbH ',
    '5068': 'Philips Lighting BV ',
    '5070': 'Show Light Oy ',
    '5071': 'Raindrop-Media ',
    '5072': 'ARRI Rental Deutschland GmbH ',
    '5075': 'Pulsar Light of Cambridge Ltd. ',
    '5099': 'Altec Di Gregorio Andrea ',
    '5100': 'Luxibel ',
    '5101': 'LBT Electronics Pvt. Ltd. ',
    '5102': 'INDATA d.o.o. ',
    '512D': 'DJPOWER ELECTRONIC STAGE LIGHTING FIXTURE FACTORY (GUANGZHOU) ',
    '5149': 'JAP Optoelectronic Ltd. ',
    '514D': 'QMAXZ lighting ',
    '5153': 'QuickSilver Controls, Inc. ',
    '5168': 'Shenzhen Sunricher Technology Co.,Ltd. ',
    '516C': 'Quicklights ',
    '51D7': 'Innovative Dimmers LLC (Ratpac dimmers) ',
    '51D8': 'Amperor Electronics (Shenzhen) Co., Ltd. ',
    '5200': 'Shenzhen Aotian Technology Co. , Ltd.  ',
    '5201': 'Crestron Electronics, Inc. ',
    '5244': 'Revolution Display ',
    '524C': 'Radical Lighting Ltd. ',
    '524D': 'RUIZ TECH ',
    '524E': 'RNC Systems Inc. ',
    '5250': 'RootPath Ltd. ',
    '5252': 'RoscoLab Ltd. ',
    '5253': 'Robe Show Lighting s.r.o. ',
    '5341': 'Stage Technologies Limited ',
    '5342': 'Industrias Sola Basic S.A. de C.V. ',
    '5343': 'Ocean Thin Films Inc. ',
    '5344': 'Stardraw.com Ltd. ',
    '5345': 'Selador ',
    '5346': 'Synthe FX, LLC ',
    '5347': 'SGM Technology For Lighting SPA ',
    '5348': 'Schreder ',
    '5349': 'Soundsculpture Incorporated ',
    '534A': 'SAS Productions ',
    '534B': 'SK-Software ',
    '534C': 'SOUNDLIGHT ',
    '534E': 'Sand Network Systems ',
    '5353': 'Sean Sill ',
    '5354': 'Stagetronics Ltda ',
    '5356': 'OOO SAMLIGHT ',
    '5363': 'SpaceCannon vH ',
    '5368': 'ShowCAD Control Systems Ltd. ',
    '536C': 'StageLine Electronic ',
    '5370': 'Chroma-Q ',
    '5374': 'STG-Beikirch Industrieelektronik + Sicherheitstechnik GmbH & Co. KG ',
    '5376': 'SV-wtu eU ',
    '5377': 'SWISSON AG ',
    '53A8': 'Simon Tech ',
    '5431': 'AUTOLUX Handels- und ProduktionsgmbH ',
    '5441': 'TecArt Lighting  ',
    '5444': 'Technographic Displays Ltd. ',
    '5445': 'TESI Elettronica srl ',
    '544C': 'Tempest Lighting Inc. ',
    '5453': 'TalentStorm Enterprises, Inc. ',
    '5454': 'TamaTech Labo Company Ltd, ',
    '5459': 'TDE-Lighttech B.V. ',
    '5550': 'UP-LUX Eletronica Ltda. ',
    '5555': 'Martin Sukale Medientechnik GbR ',
    '55AA': 'Emilum GmbH ',
    '564C': 'Vari-Lite, Inc. ',
    '5651': 'Vision Quest Lighting Inc. ',
    '5652': 'Megapixel Visual Reality ',
    '5653': 'Viso Systems Aps ',
    '5655': 'Shenzhen CAS VU Technologies Co., Ltd. ',
    '5744': 'W-DEV ',
    '5746': 'Wildfire, Inc. ',
    '5747': 'Wenger / JR Clancy ',
    '5753': 'Wireless Solution Sweden AB ',
    '5754': 'LIGHTMAN (Interlite AB) ',
    '5759': 'Wybron, Inc. ',
    '584C': 'X-Laser ',
    '584D': 'Xtraordinary Musical Accolade Systems ',
    '5858': 'Illuminance Technologies ',
    '5865': 'XENON ARCHITECTURAL LIGHTING ',
    '586C': 'Eurolumen (Shanghai) Lighting Co., LTD ',
    '586D': 'www.doityourselfchristmas.com hobbyists ',
    '5888': 'Plsao Optoelectronics Technology Co., Ltd. ',
    '5A53': 'Zingerli Show Engineering ',
    '5C40': 'OXO ',
    '5D00': 'L1 Inc. ',
    '5D01': 'MTS Medientechnik GmbH ',
    '5D02': 'Underwater Lights Limited ',
    '5DAC': 'Mediatec Group ',
    '5E5D': 'Multisenses GmbH ',
    '6100': 'Krobox Sdn Bhd ',
    '610A': 'Visenge Pty. Ltd  ',
    '6123': 'CMYLight (S) Pte. Ltd. ',
    '6124': 'Fiilex ',
    '614C': 'Alektra AB ',
    '6154': 'Advatek Lighting ',
    '6164': 'AVID Labs ',
    '616C': 'Advanced Lighting Systems ',
    '6200': 'LUCITAG Ltd.  ',
    '6201': 'NuDelta Digital, LLC ',
    '6202': 'ESCO Sp. z o.o. ',
    '6203': 'Flektor  ',
    '6204': 'Shenzhen Absen Optoelectronic Co., Ltd ',
    '6205': 'Zhuhai Ltech Technology Co., Ltd. ',
    '6206': 'Lighting Innovation Company, LLC ',
    '6273': 'B&S Elektronische Geräte GmbH ',
    '6342': 'Mega Systems Inc. ',
    '6364': 'CDS advanced technology bv ',
    '641A': 'Heliospectra AB ',
    '6461': 'Digilin Australia ',
    '6464': 'Dangeross Design ',
    '646C': 'dilitronics GmbH ',
    '646F': 'eldoLED BV ',
    '64B9': 'Finelite, Inc. ',
    '6542': 'eBrain GmbH ',
    '6547': 'euroGenie ',
    '6553': 'EtherShow ',
    '6555': 'Shantea Controls ',
    '6565': 'Stratus Systems LLC ',
    '656C': 'ELC lighting ',
    '6573': 'Environmental Lighting Solutions ',
    '6574': 'Electronic Theatre Controls, Inc. ',
    '6576': 'eventa Aktiengesellschaft ',
    '6644': 'Sunlab Technologies S.L. ',
    '666D': 'MAD-Effects ',
    '6673': 'Freescale Semiconductor U.K. Ltd. ',
    '6756': 'Lumisia Co., Ltd. ',
    '676C': 'GLP German Light Products GmbH ',
    '67F0': 'Toshiba Lighting & Technology Corporation ',
    '6816': 'ChamberPlus Co., Ltd ',
    '6864': 'James Embedded Systems Engineering (JESE Ltd) ',
    '6865': 'Hubbell Entertainment, Inc. ',
    '686C': 'HERA LED ',
    '694C': 'iLight Technologies Inc ',
    '6969': 'Better Way Lighting ',
    '6974': 'Ittermann electronic GmbH ',
    '6A6A': 'Roxx GmbH ',
    '6A6B': 'JPK Systems Limited ',
    '6B64': 'Key Delfin ',
    '6B69': 'Magical Fountain SA de CV (Magic Fountain) ',
    '6BEE': 'Ephesus Lighting ',
    '6BEF': 'Shenzhen Ifountain Technology Ltd. ',
    '6C6D': 'Zumtobel Lighting GmbH ',
    '6C78': 'Claude Heintz Design ',
    '6C92': 'Ambra Elettronica s.r.l. ',
    '6D61': 'MAL Effekt-Technik GmbH ',
    '6D62': 'MBN GmbH ',
    '6D63': 'Sein & Schein GmbH ',
    '6E00': 'LEDeco solution, s.r.o. ',
    '6F00': 'Guangzhou Huaying Stage Lighting Equipment Co. Ltd. ',
    '6F01': 'DAVAI!JPL ',
    '6F02': 'hazebase (Uta Raabe e.K.) ',
    '6FEA': 'Lumina Visual Productions ',
    '6FEB': 'Insight Lighting ',
    '6FEC': 'Arc Lighting Co. Ltd. ',
    '6FED': 'Explorentis ',
    '7000': 'Nippon Ceramic Co., Ltd. ',
    '700A': 'Guangzhou Leemc Lighting Tech., Co., Ltd. ',
    '700B': 'Vice Lighting DWC LLC ',
    '7068': 'Pharos Architectural Controls ',
    '7070': 'SBT GmbH ',
    '7072': 'Pr-Lighting Ltd. ',
    '7078': 'PixelRange Inc. ',
    '70F0': 'Pangolin Laser Systems, Inc.  ',
    '7151': 'The Light Source, Inc. ',
    '7363': 'Sean Christopher FX ',
    '7365': 'Ballantyne Strong Inc. ',
    '736C': 'Strand Lighting Ltd. ',
    '7400': 'Danalux ',
    '7764': 'WET ',
    '7765': 'MKT engineering GmbH & Co. KG ',
    '7777': 'Develtron A/S ',
    '7788': 'DigitaLicht AG ',
    '780E': 'Mole-Richardson Co. ',
    '783A': 'Audiolux Devices LLC ',
    '786C': 'XLN-t bvba ',
    '7888': 'Tontron Photoelectric Co., Limited ',
    '78B4': 'LED Flex Limited ',
    '7900': 'Leprecon / CAE, Inc. ',
    '79BC': 'DC Reactive ',
    '7A70': 'Open Lighting ',
    '7AA0': 'Anaren Inc. ',
    '7AAA': 'WEAD (Wagner Electronic and Design) ',
    '7AAB': 'Hyundai Fomex Co., Ltd. ',
    '7B1B': 'DimLight Ltd. ',
    '7D61': 'HMB|TEC GmbH ',
    '7DE7': 'Guangzhou ILightings Equipment Co., Ltd. ',
    '7DE8': 'Shenzhen LAMP Technology Co., Ltd. ',
    '7DEE': 'zencontrol Pty Ltd ',
    '7EE7': 'Arthur Digital Solutions Kft ',
    '7EE8': 'Guangzhou Yingfeng Lighting Equipment Co., Ltd. ',
    '7EE9': 'Technology Kitchen ',
    '7EEA': 'Cartwright Engineering  ',
    '7EEB': 'mylaserpage ',
    '7EEC': 'SHENZHEN LP Display ',
    '7EED': 'Look Solutions GmbH & Co. KG ',
    '7EEE': 'General Lighting Electronic Co., Ltd. ',
    '7EEF': 'Huizhou Mounteck Technology Co., Ltd. ',
    '7FF0': 'RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY ',
    '7FF1': 'RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY ',
    '7FF2': 'RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY ',
    '7FF3': 'RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY ',
    '7FF4': 'RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY ',
    '7FF5': 'RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY ',
    '7FF6': 'RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY ',
    '7FF7': 'RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY ',
    '7FF8': 'RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY ',
    '7FF9': 'RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY ',
    '7FFA': 'RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY ',
    '7FFB': 'RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY ',
    '7FFC': 'RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY ',
    '7FFD': 'RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY ',
    '7FFE': 'RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY ',
    '7FFF': 'RESERVED FOR PROTOTYPING/EXPERIMENTAL USE ONLY ',
    'FFFF': 'ESTA ',
}